const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  CUSTOMER: 'CUSTOMER',
};

const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
};

const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTHENTICATION_ERROR: 'UNAUTHORIZED_ACCESS',
  AUTHORIZATION_ERROR: 'ACCESS_DENIED',
  NOT_FOUND: 'RESOURCE_NOT_FOUND',
  DUPLICATE_DATA: 'RESOURCE_ALREADY_EXISTS',
  DATABASE_ERROR: 'DATABASE_OPERATION_FAILED',
  BUSINESS_RULE_ERROR: 'BUSINESS_RULE_VIOLATION',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
};

module.exports = {
  ROLES,
  HTTP_STATUS,
  ERROR_CODES,
};
