const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  CUSTOMER: 'CUSTOMER',
};

const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
};

const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTHENTICATION_ERROR: 'UNAUTHORIZED_ACCESS',
  AUTHORIZATION_ERROR: 'ACCESS_DENIED',
  NOT_FOUND: 'RESOURCE_NOT_FOUND',
  DUPLICATE_DATA: 'RESOURCE_ALREADY_EXISTS',
  DATABASE_ERROR: 'DATABASE_OPERATION_FAILED',
  BUSINESS_RULE_ERROR: 'BUSINESS_RULE_VIOLATION',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

  // Module 3 Error Codes
  BRAND_NOT_FOUND: 'BRAND_NOT_FOUND',
  BRAND_ALREADY_EXISTS: 'BRAND_ALREADY_EXISTS',
  BRAND_INACTIVE: 'BRAND_INACTIVE',
  MOBILE_NOT_FOUND: 'MOBILE_NOT_FOUND',
  MOBILE_ALREADY_EXISTS: 'MOBILE_ALREADY_EXISTS',
  INVALID_MOBILE_PRICE: 'INVALID_MOBILE_PRICE',
  INVALID_BRAND: 'INVALID_BRAND',
  IMAGE_NOT_FOUND: 'IMAGE_NOT_FOUND',
  PRIMARY_IMAGE_ERROR: 'PRIMARY_IMAGE_ERROR',

  // Module 4 Error Codes
  PART_CATEGORY_NOT_FOUND: 'PART_CATEGORY_NOT_FOUND',
  PART_CATEGORY_ALREADY_EXISTS: 'PART_CATEGORY_ALREADY_EXISTS',
  PART_CATEGORY_INACTIVE: 'PART_CATEGORY_INACTIVE',
  PART_NOT_FOUND: 'PART_NOT_FOUND',
  PART_ALREADY_EXISTS: 'PART_ALREADY_EXISTS',
  PART_NUMBER_ALREADY_EXISTS: 'PART_NUMBER_ALREADY_EXISTS',
  INVALID_PART_PRICE: 'INVALID_PART_PRICE',
  INVALID_QUANTITY: 'INVALID_QUANTITY',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  INVENTORY_TRANSACTION_FAILED: 'INVENTORY_TRANSACTION_FAILED',
  INVALID_STOCK_ADJUSTMENT: 'INVALID_STOCK_ADJUSTMENT',

  // Module 6 Error Codes
  ENQUIRY_NOT_FOUND: 'ENQUIRY_NOT_FOUND',
  ENQUIRY_ACCESS_DENIED: 'ENQUIRY_ACCESS_DENIED',
  INVALID_ENQUIRY_STATUS: 'INVALID_ENQUIRY_STATUS',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  ENQUIRY_ALREADY_RESOLVED: 'ENQUIRY_ALREADY_RESOLVED',
  ENQUIRY_ALREADY_CANCELLED: 'ENQUIRY_ALREADY_CANCELLED',
  EMPTY_ENQUIRY_RESPONSE: 'EMPTY_ENQUIRY_RESPONSE',
  INVALID_ENQUIRY_DATA: 'INVALID_ENQUIRY_DATA',

  // Module 7 Error Codes
  REQUEST_NOT_FOUND: 'REQUEST_NOT_FOUND',
  REQUEST_ACCESS_DENIED: 'REQUEST_ACCESS_DENIED',
  INVALID_REQUEST_TYPE: 'INVALID_REQUEST_TYPE',
  INVALID_REQUEST_QUANTITY: 'INVALID_REQUEST_QUANTITY',
  MOBILE_NOT_AVAILABLE: 'MOBILE_NOT_AVAILABLE',
  PART_NOT_AVAILABLE: 'PART_NOT_AVAILABLE',
  INVALID_REQUEST_STATUS: 'INVALID_REQUEST_STATUS',
  REQUEST_ALREADY_COMPLETED: 'REQUEST_ALREADY_COMPLETED',
  REQUEST_ALREADY_CANCELLED: 'REQUEST_ALREADY_CANCELLED',
  REQUEST_CANNOT_BE_CANCELLED: 'REQUEST_CANNOT_BE_CANCELLED',
};

module.exports = {
  ROLES,
  HTTP_STATUS,
  ERROR_CODES,
};
